services:
  api_backend:
    build: .
    container_name: back-api
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    volumes:
      - .:/app
  postgresql:
    container_name: 'pilula-db'
    image: postgres:16
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "15432:5432"
